### ISSUE TITLE
How to use CachedXMLHttpRequest? There is no documentation.

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [kongregate/Unity-WebGL-Utilities#2]
_Remember: This is not an issue_ 

I am loading/unloading asset bundle using _`WWW.LoadFromCacheOrDownload`_ this method but after getting some loading/unloading chrome shown an error **Fix "Aw, Snap!" page crashes** problem. So i try to search and found your blog [here](https://blog.kongregate.com/unity-webgl-memory-optimization-part-deux/). After reading i think that i have asset bundle caching issue like post said

> What you might not realize is that this virtual filesystem is loaded into and persisted in memory as soon as your Unity application starts. This means that if you are using the default Unity caching mechanism for Asset Bundles, you are adding the size of all of those bundles to the memory requirements for your game, even if they are not being loaded.

(If i am wrong please correct me remember i am getting aw snap error not memory error).
So now i am trying to use `CachedXMLHttpRequest` but there is no documentation that how to use it.

**Comment by BenV** [comment]
You can find the original documentation from Unity's `CachedXMLHttpRequest` [here](https://github.com/kongregate/Unity-WebGL-Utilities/tree/master/Assets/Plugins/WebGLCachedXMLHttpRequest) in their readme.txt file. Our version is a drop-in replacement that resolves some issues and adds some extra functionality.

**Comment by MuhammadFaizanKhan** [comment]
> drop-in replacement

Thanks for reply. It means that any request through WWW or WebRequest class will automatically take over by the plugin, so in this perspective, this code snippet is valid?
`    IEnumerator DownloadAndCache(string bundleURL, string assetName = "")
    { 
        // get current bundle hash from server, random value added to avoid caching
        UnityWebRequest www;
        www = UnityWebRequestAssetBundle.GetAssetBundle(bundleURL);
        yield return www.SendWebRequest();

        if (www.error != null)
        {
            Debug.LogError("www error: " + www.error);
            www.Dispose();
            www = null;
            yield break;
        }

        // get bundle from downloadhandler
        AssetBundle bundle = ((DownloadHandlerAssetBundle)www.downloadHandler).assetBundle;
        GameObject bundlePrefab = null;

        // if no asset name is given, take the first/main asset
        if (assetName == "")
        {
            bundlePrefab = (GameObject)bundle.LoadAsset(bundle.GetAllAssetNames()[0]);
        }
        else
        { // use asset name to access inside bundle
            bundlePrefab = (GameObject)bundle.LoadAsset(assetName);
        }

        // if we got something out
        if (bundlePrefab != null)
        {
            GameObject abObject = (GameObject)Instantiate(bundlePrefab, gameObject.transform.position, gameObject.transform.rotation);
            abObject.transform.parent = this.transform;
            if (AssetBundleLoadedAndInstantiated != null)
            {
                AssetBundleLoadedAndInstantiated(this.name);
            }
        }

        www.Dispose();
        www = null;
        // try to cleanup memory
        Resources.UnloadUnusedAssets();
        bundle.Unload(false);
        bundle = null;
    }`

**Comment by BenV** [comment]
I believe that is correct, although it has been nearly 2 years since I have really looked into it. From what I recall you should be able to see `CachedXMLHTTPRequest` entries in the console logs when downloading assets to confirm it is functioning properly.

**Comment by MuhammadFaizanKhan** [comment]
Whenever i load the website i got this message
CachedXHRExtensions initialized, enabled=true

And when  i load the bundle with above given code snippet i got this message:
[CachedXMLHttpRequest] 'myurl address served from indexedDB cache (30612555 bytes)

**Comment by thekrantz** [comment]
Hi. im already following inctruction but i still got error. My chrome got Aw, Snap! Page. But in console show [CachedXMLHttpRequest] 'url' downloaded successfully (460127393 bytes) and stored in indexedDB cache.
